### ISSUE TITLE
Readme of mcp to be improved, not so clear 

### ISSUE THREAD

**Issue by Lyreplus** [eagletrt/micro-libs#21]
From [Readme](https://github.com/eagletrt/micro-libs/tree/master/mcp23017)
For example
```C
#include <stdint.h>
 
uint8_t mcp23017_device_address = 0x00;
uint8_t mcp23017_i2c_timeout = 10;
```

Maybe it would be better to say that you have to insert the device address 

And, read and write paragraph: should we have to insert these snippets into our code? If we have to use only the interrupt shouln't we just use read? And maybe a todo list for using these lines of code would be pretty useful.  

I.e.: 1- add device address, 2- find from the datasheet the gpinten_register_value and the other variables' values. 3- Depending on your use cases use only these or those lines of code, ...  

Moreover, I've read the docs in the header file but still isn't clear when to use which variable and why (for instance in the steering wheel repo, manettini_fix branch, we've only used gpinten_register_value, why?)

**Comment by Kalsifer-742** [comment]
Updated documentation. Please provide feedback.

**Comment by Kalsifer-742** [comment]
Documentation on how to determine the address of the device is incorrect

**Comment by Kalsifer-742** [comment]
Fixed missing information on address plus general improvement.
